services:
  db:
    image: postgres:alpine
    container_name: blogchain_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgresql/data

volumes:
  postgres:
