POST http://localhost:3000/post
Content-Type: application/json

{
  "title":"Test post for this",
  "type":"post",
  "slug":"test-post-for-this",
  "status":"draft",
  "content":"SHit hists hard",
  "schema":"{\r\n \"@context\":\"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
  "featuredImageUrl":"https://picsum.photos/200",
  "publishOn":"2024-03-16T07:46:32+0000",
  "tags": ["saiko", "kawa"],
  "metaOptions":[
    {
      "key":"test",
      "value":"esys"
    }
  ]
}