POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Sample Post for Tags",
    "type": "post",
    "slug": "sample-tagg-r-tagd",
    "status": "draft",
    "content": "Sample content for tags.",
    "schema":"{\r\n \"@context\":\"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
    "featuredImageUrl": "https://picsum.photos/200",
    "publishOn": "2024-03-16T07:46:32+0000",
    "metaOptions":{
      "metaValue":"{\"sidebarEnabled\":true}"
    },
    "authorId":6,
    "tags":[6,7] 
  }