POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiamFrZUBnbWFpbC5jb20iLCJpYXQiOjE3Mjk4NjEwNDYsImV4cCI6MTcyOTg2NDY0NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.ZTdE2QtTMJeuMbne-zC4V2gOKoWImPEbby9bYiPpngo

{
    "title": "Sample Post for Tags",
    "type": "post",
    "slug": "sample-tagg-r-tagdf",
    "status": "draft",
    "content": "Sample content for tags.",
    "schema":"{\r\n \"@context\":\"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n}",
    "featuredImageUrl": "https://picsum.photos/200",
    "publishOn": "2024-03-16T07:46:32+0000",
    "metaOptions":{
      "metaValue":"{\"sidebarEnabled\":true}"
    },
    "tags":[1]
  }